version: "3.8"

services:
  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6680:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend Express API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6600:6600" # Assuming your Node app listens on 6600 inside the container
    # Load environment variables from .env file
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Use the Atlas connection string, substituting the password from the .env file
      - MONGODB_URI=mongodb+srv://inviteApp_prod:${MONGO_ATLAS_PASSWORD}@cluster0.g0ffsht.mongodb.net/?retryWrites=true&w=majority&appName=cluster0
      - CORS_ORIGIN=http://localhost:6680 # Adjust if needed
    networks:
      - app-network
    restart: unless-stopped
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: # Optional: Remove if mongodb service is removed
